"use client"
import Link from "next/link";
import { usePathname } from "next/navigation";
import "./style.css"

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

const Navlinks = [
  { name: "Login", href: "/login" },
  { name: "Register", href: "/register" },
  { name: "Forgot Password", href: "/forgot-password" },
];

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "red",
          }}
        >
          Header Content
        </header>
        {Navlinks.map((link) => {
          const isActive =
            pathName === link.href ||
            (pathName.startsWith(link.href) && link.href !== "/");
          return (
            <Link
              href={link.href}
              key={link.name}
              className={isActive ? "font-bold mr-4" : "text-blue-500 mr-4"}
            >
              {link.name}
            </Link>
          );
        })}
        {children}
      </body>
    </html>
  );
}
