export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function TestLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer
          style={{
            backgroundColor: "blue",
          }}
        >
          Footer content
        </footer>
      </body>
    </html>
  );
}
