import { Metadata } from "next";

export const metadata:Metadata = {
  title: {
    default:"Next.js", // This is the default metadata title if pages don't have it.
    template:"%s - Practice", //This adds the "-practice" as suffix if a page already has a metadata title.
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
